# Generated by Django 3.1.4 on 2020-12-02 13:26

import accounts.models
from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='不得超过128个字符，包含字母、数字，特殊字符仅@、+、-、_', max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(help_text='一个邮箱只能注册一次', max_length=254, unique=True, verbose_name='邮箱')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('gender', models.CharField(blank=True, choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='1', max_length=3, null=True, verbose_name='性别')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='地址')),
                ('identified_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='身份证')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y%m%d/', verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='电话')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='生成日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否为员工')),
                ('personal_profile', models.TextField(blank=True, help_text='不得超过500字!', max_length=500, null=True, verbose_name='个人简介')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['created_time'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
